version: '3.7'
services:
  load-balancer:
    image: ecr.url/image.name:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - api_network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      WAIT_HOSTS: backend_service:8000
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == manager

networks:
  api_network:
    external: true
configs:
  env-production:
    external: true
